name: anixart
description: Anixart client — Flutter port of the Android app UI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0
  video_player: ^2.9.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
